export const languages = [
    { "code": "en", "name": "English" },
    { "code": "es", "name": "Spanish" },
    { "code": "fr", "name": "French" },
    { "code": "de", "name": "German" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "it", "name": "Italian" },
    { "code": "pl", "name": "Polish" },
    { "code": "nl", "name": "Dutch" },
    { "code": "sv", "name": "Swedish" },
    { "code": "fi", "name": "Finnish" },
    { "code": "da", "name": "Danish" },
    { "code": "cs", "name": "Czech" },
    { "code": "ro", "name": "Romanian" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "sk", "name": "Slovak" },
    { "code": "et", "name": "Estonian" },
    { "code": "lt", "name": "Lithuanian" },
    { "code": "ja", "name": "Japanese" },
    { "code": "sl", "name": "Slovenian" },
    { "code": "hr", "name": "Croatian" },
    { "code": "sq", "name": "Albanian" },
    { "code": "sr", "name": "Serbian" },
    { "code": "tr", "name": "Turkish" },
    { "code": "uk", "name": "Ukrainian" },
    { "code": "ga", "name": "Irish" },
]

